openapi: 3.0.0
info:
  title: Urban Farming API
  version: 1.0.0

servers:
  - url: http://localhost:5000

paths:
  # ================= AUTH =================

  /api/v1/auth/register:
    post:
      summary: Register user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User created

  /api/v1/auth/login:
    post:
      summary: User login
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful

  # ================= VENDOR =================

  /api/v1/vendors:
    post:
      summary: Create vendor profile
      tags: [Vendor]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - farmName
                - farmLocation
              properties:
                farmName:
                  type: string
                farmLocation:
                  type: string
      responses:
        "201":
          description: Vendor created

    get:
      summary: Get all vendors
      tags: [Vendor]
      responses:
        "200":
          description: Vendors fetched

  # ================= CATEGORY =================
  /api/v1/categories:
    post:
      summary: Create category (Admin only)
      tags: [Category]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Category created

    get:
      summary: Get all categories
      tags: [Category]
      responses:
        "200":
          description: Categories fetched successfully

  # ================= PRODUCT =================

  /api/v1/products:
    get:
      summary: Get all products (filter + pagination)
      tags: [Product]
      parameters:
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: categoryId
          schema:
            type: string
        - in: query
          name: vendorId
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: number
        - in: query
          name: limit
          schema:
            type: number
      responses:
        "200":
          description: Products fetched

    post:
      summary: Create product (Vendor only)
      tags: [Product]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - price
                - quantity
                - categoryId
              properties:
                name:
                  type: string
                price:
                  type: number
                quantity:
                  type: number
                description:
                  type: string
                categoryId:
                  type: string
      responses:
        "201":
          description: Product created

  # ================= CART =================
  /api/v1/cart:
    post:
      summary: Add product to cart
      tags: [Cart]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
                - quantity
              properties:
                productId:
                  type: string
                  example: "uuid-product-id"
                quantity:
                  type: number
                  example: 2
      responses:
        "201":
          description: Item added to cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object

    get:
      summary: Get my cart
      tags: [Cart]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Cart fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object

  /api/v1/cart/{productId}:
    delete:
      summary: Remove item from cart
      tags: [Cart]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Item removed from cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object

  # ================= ORDER =================

  /api/v1/orders:
    post:
      summary: Create Order from Cart
      tags: [Order]
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      userId:
                        type: string
                      total:
                        type: number
                      status:
                        type: string
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            productId:
                              type: string
                            quantity:
                              type: number
                            price:
                              type: number

    get:
      summary: Get My Orders
      tags: [Order]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Orders fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        total:
                          type: number
                        status:
                          type: string
                        createdAt:
                          type: string

  # ================= RENTAL =================
  /api/v1/rentals:
    post:
      summary: Create Farm Space
      tags: [Rental]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, location, size, pricePerDay]
              properties:
                title:
                  type: string
                  example: "Organic Farm Plot"
                location:
                  type: string
                  example: "Dhaka"
                size:
                  type: number
                  example: 100
                pricePerDay:
                  type: number
                  example: 500
      responses:
        "201":
          description: Farm space created successfully
          content:
            application/json:
              schema:
                type: object

    get:
      summary: Get All Farm Spaces
      tags: [Rental]
      responses:
        "200":
          description: Spaces fetched successfully
          content:
            application/json:
              schema:
                type: object

  /api/v1/rentals/book:
    post:
      summary: Book Farm Space
      tags: [Rental]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [spaceId, startDate, endDate]
              properties:
                spaceId:
                  type: string
                  example: "uuid-space-id"
                startDate:
                  type: string
                  example: "2026-04-20"
                endDate:
                  type: string
                  example: "2026-04-25"
      responses:
        "201":
          description: Space booked successfully
          content:
            application/json:
              schema:
                type: object

  # ================= CERTIFICATION =================
  /api/v1/certifications:
    post:
      summary: Submit Certification
      tags: [Certification]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - certifyingAgency
                - certificationDate
              properties:
                certifyingAgency:
                  type: string
                  example: "Organic Board BD"
                certificationDate:
                  type: string
                  example: "2026-04-18"
      responses:
        "201":
          description: Certification submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                    example: 201
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Certification submitted"
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      vendorId:
                        type: string
                      certifyingAgency:
                        type: string
                      certificationDate:
                        type: string

    get:
      summary: Get all certifications (Admin)
      tags: [Certification]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Certifications fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                    example: 200
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Certifications fetched successfully"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        vendorId:
                          type: string
                        certifyingAgency:
                          type: string
                        certificationDate:
                          type: string

  # ================= COMMUNITY =================
  /api/v1/community:
    post:
      summary: Create community post
      tags: [Community]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - postContent
              properties:
                postContent:
                  type: string
                  example: "Best organic farming tips for beginners"
      responses:
        "201":
          description: Post created successfully

    get:
      summary: Get all community posts
      tags: [Community]
      responses:
        "200":
          description: Posts fetched successfully

  # ================= SECURITY =================
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
